### ISSUE TITLE
Two customer cart is merging

### ISSUE THREAD

**Issue by nehaaccorin** [magefan/module-login-as-customer#32]
Hey,

I am login as customer 1 and add 2 product in cart. after that i am login as customer 2 (does not have any item in cart) then customer 1 cart item merge in customer 2 cart.

Can you please provide solution for that, I don't want to merge cart.

**Comment by magefan** [comment]
@nehaaccorin ,

Thank you for your report.
Can you please let us know1
1) Your Magento Edition
2) Your Magento Version
3) Extension versions

**Comment by nehaaccorin** [comment]
1. enterprise edition
2. 2.2.6
3. 2.1.8

**Comment by magefan** [comment]
Thank you for clarification. Think this is because you using the old [Magento 2 Login As Customer](https://magefan.com/login-as-customer-magento-2-extension) extension version. We cannot reproduce the issue on latest extension v2.2.1
You can also check on our [demo](https://lac.demo.magefan.top/admin)

P.S.: As you use Magento EE, then after the update it may require a product key, is so, please [check this article](https://magefan.com/blog/product-key-is-empty-or-invalid)

**Comment by nehaaccorin** [comment]
Demo link is not working, For latest module we have to purchase it. can you provide working demo url?

**Comment by magefan** [comment]
@nehaaccorin , 
Demo URL: https://lac.demo.magefan.top/admin/admin/
If you don't have the product key for EE then yes, you'll need to purchase the extension for EE at our store https://magefan.com/login-as-customer-magento-2-extension

**Comment by nehaaccorin** [comment]
Thank you!
