### ISSUE TITLE
How to get the Product Key for free new version?

### ISSUE THREAD

**Issue by hkvega01** [magefan/module-login-as-customer#35]
Is this plugin still providing free product key for new version?

**Comment by ihorvansach** [comment]
@hkvega01 ,
[Magento 2 Login As Customer Extension](https://magefan.com/login-as-customer-magento-2-extension) is free for Magento Community Edition, if you have any issues with enabling the extension on Magento CE, please check this article:
[https://magefan.com/blog/product-key-is-empty-or-invalid ](https://magefan.com/blog/product-key-is-empty-or-invalid )

As for Magento Enterprise
Magefan extensions are paid for Magento EE, but until some versions, we didn't require a product key. Developers were able to download them from GitHub or other open places and use them without actually paying.
More details you can find here:
[https://magefan.com/blog/product-key-is-empty-or-invalid#ee](https://magefan.com/blog/product-key-is-empty-or-invalid#ee)

**Comment by WinstonN** [comment]
@ihorvansach I completely understand why you took this approach, but, if I put myself into the shoes of an EE customer, that already uses your module, because it was on github, and now suddenly, with **no clear and open publicly available communication** to require a product key, is a bit of a surprise. To put it lightly. 

Looking into what's going on here under the hood, I see things like the below. Which is "questionable" practices, and that immediately get's you banned on all of my sites. 

![image](https://user-images.githubusercontent.com/1143789/77016376-55b70200-69dc-11ea-9bc1-f48e398e3dba.png)
![image](https://user-images.githubusercontent.com/1143789/77016379-5b144c80-69dc-11ea-83ac-d1b218fb7cda.png)

See the string reverse you are doing? See how you hide and obscure code. You could literally be sucking everything out of a store, and no one would be the wiser, unless, we have a look under the hood as I did.

A little piece of advice, if I may. Decide in which camp you want your image to be. Do you want to be a friend of Magento Developers, Merchants? If so,  practices like these, are extremely risky for you, and are frown upon by any person with a backbone.

Just my 2 cents..

**Comment by ihorvansach** [comment]
@WinstonN , 

Magefan extensions are paid for Magento EE, but until some versions, we didn't require a product key. Developers were able to download them from GitHub or other open places and use without actually paying. In the latest versions, there is added the product key field. If you use a free version (do not have any paid orders) you need to purchase [Magefan extension](https://magefan.com/magento2-extensions) for EE to be able to use the recent version. 

FAQ
What is the difference between Magefan extension for Magento Community and Magento Enterprise, why it is not free fro Enterprise?

 - Magefan extensions code was made to be completely the same as for Magento Community (CE) and Magento Enterprise (EE). We made one extension (code) for both Magento editions to maintain it easier. Magento EE has additional functionality (modules), one of the examples is a page builder or catalog restrictions, and in our code, we made sure the extension does not conflict with them and works properly. A module included EE only specific code, that's why it the same code, but it is free for Magento CE and paid for Magento EE.

@WinstonN , you can complete FREE use our Login As Customer extension on Magento Community, if you don't like to pay for Login As Customer for Magento EE, you can use any other extension. As for your code review suggestions, we refactoring the code right now and soon you'll see a new extension version.

**Comment by peterjaap** [comment]
Sjeez this is terrible practice. I'll be swapping out this extension by one of your competitors.
